
- hosts: (ip)
  gather_facts: false
  vars_files: 
    - (path to creds folder)/credentials/credentials_junos.yaml
  vars: 
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: junipernetworks.junos.junos

    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks: 
    - name: configuring trunk port ge-0/0/45 with allowed vlans 
      junipernetworks.junos.junos_l2_interfaces: 
        config: 
          - name: ge-0/0/45
            enhanced_layer: false
            unit: 0 
            trunk: 
              allowed_vlans: 
        state: replaced

- hosts: (ip)
  gather_facts: false
  vars_files: 
    - (path to creds folder)/credentials/credentials_nxos.yaml
  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos

    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks: 
      - name: backup current config
        cisco.nxos.nxos_config: 
          backup: true
          backup_options: 
            dir_path: backups/
            filename: backup_(ip)

      - name: reset default interface Ethernet1/1
        cisco.nxos.nxos_config: 
          lines: default interface Ethernet1/1 

 
      - name: configure access/trunk VLANs on interface Ethernet1/1 
        cisco.nxos.nxos_config: 
          lines: 
            - switchport
            - switchport mode trunk
            - switchport trunk allowed vlan 1,30-40
            - no shutdown
          parents: interface Ethernet1/1
          save_when: changed



- hosts: (ip)
  gather_facts: false
  vars_files: 
    - (path to creds folder)/credentials/credentials_nxos.yaml
  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos

    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks: 
      - name: backup current config
        cisco.nxos.nxos_config: 
          backup: true
          backup_options: 
            dir_path: backups/
            filename: backup_(ip)

      - name: reset default interface Ethernet1/51
        cisco.nxos.nxos_config: 
          lines: default interface Ethernet1/51 

 
      - name: configure access/trunk VLANs on interface Ethernet1/51 
        cisco.nxos.nxos_config: 
          lines: 
            - switchport
            - switchport access vlan 1
            - no shutdown
          parents: interface Ethernet1/51
      - name: reset default interface Ethernet1/51
        cisco.nxos.nxos_config: 
          lines: default interface Ethernet1/51 

 
      - name: configure access/trunk VLANs on interface Ethernet1/51 
        cisco.nxos.nxos_config: 
          lines: 
            - switchport
            - switchport access vlan 1
            - no shutdown
          parents: interface Ethernet1/51
          save_when: changed



- hosts: (ip)
  gather_facts: false
  vars_files: 
    - (path to creds folder)/credentials/credentials_junos.yaml
  vars: 
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: junipernetworks.junos.junos

    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks: 
    - name: configuring access port ge-0/0/43 in vlan default
      junipernetworks.junos.junos_l2_interfaces: 
        config: 
          - name: ge-0/0/43
            enhanced_layer: true
            unit: 0
            access: 
              vlan: default
        state: replaced
    - name: configuring access port ge-0/0/45 in vlan default
      junipernetworks.junos.junos_l2_interfaces: 
        config: 
          - name: ge-0/0/45
            enhanced_layer: true
            unit: 0
            access: 
              vlan: default
        state: replaced
        