- hosts: (hostname for debian based systems) 
  gather_facts: false
  vars_files: 
    - (secrets file path)

  vars: 
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_become_password: "{{ sudo_password }}"

  tasks: 
    - name: perform apt update 
      become: true
      ansible.builtin.apt: 
        name: "*"
        state: latest
      register: output

      
    - name: print msg 
      debug: msg="{{ output.stdout_lines }}"

- hosts: (rhel based systems) 
  gather_facts: false
  vars_files: 
    - secrets.yaml
  
  vars: 
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_become_password: "{{ sudo_password }}"

  tasks: 
    - name: update dnf
      become: true
      ansible.builtin.dnf: 
        name: "*"
        state: latest
      register: output
    
    - debug: msg="{{ output.msg }}"